# -*- coding: utf-8 -*-
"""Qiskit-5teleportation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Imt3G6T73XuZ_JysH2sLoIkEi4otLcLo

https://youtu.be/mMwovHK2NrE?si=3FH7VujFjtOuA1ND
"""

import qiskit

import numpy as np

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

circuit = qiskit.QuantumCircuit(3, 3)

#circuit.initialize([1j, 0], 0)
#circuit.initialize([1, 0], 0)
#circuit.initialize([0, 1], 0)
#circuit.initialize([-1/np.sqrt(2)+1j/np.sqrt(2), 0], 0)
#circuit.initialize([1/np.sqrt(2), -1/np.sqrt(2)], 0)

#circuit.initialize([0, 1], 1)
#circuit.initialize([0, 1], 2)

circuit.draw('mpl')

circuit.x(0)
circuit.barrier()

circuit.draw('mpl')

circuit.h(1)
circuit.cx(1, 2)

circuit.draw('mpl')

circuit.cx(0, 1)
circuit.h(0)

circuit.draw('mpl')

circuit.barrier()
circuit.measure([0,1], [0,1])

circuit.draw('mpl')

circuit.barrier()
circuit.cx(1, 2)
circuit.cz(0, 2)

circuit.draw('mpl')

circuit.measure(2, 2)

circuit.draw('mpl')

"""https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B%22X%22%5D%2C%5B1%2C%22H%22%5D%2C%5B1%2C%22%E2%80%A2%22%2C%22X%22%5D%2C%5B%22%E2%80%A2%22%2C%22X%22%5D%2C%5B%22H%22%5D%2C%5B1%2C%22%E2%80%A2%22%2C%22X%22%5D%5D%7D"""

#simulator = qiskit.Aer.get_backend('qasm_simulator')
simulator = qiskit.Aer.get_backend('statevector_simulator')
simulator

job = qiskit.execute(circuit, backend=simulator, shots=1024)
job

result = job.result()
result

counts = result.get_counts()
counts

from qiskit.tools.visualization import plot_histogram

plot_histogram(counts)

sv = result.get_statevector()
sv

from qiskit.tools.visualization import plot_bloch_multivector

plot_bloch_multivector(sv)

