# -*- coding: utf-8 -*-
"""Qiskit-4circuits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vz0NEfGB2_asCuxJbJVaa6cmaVytCXEx

https://youtu.be/tBnWG_95F9c?si=kFSYFALYIfbNZNK6
"""

import qiskit

from qiskit.tools.visualization import plot_bloch_multivector

circuit = qiskit.QuantumCircuit(1, 1)
circuit.x(0)
circuit

circuit.draw(output='mpl')

simulator = qiskit.Aer.get_backend('statevector_simulator')
simulator

job = qiskit.execute(circuit, backend=simulator)
job

result = job.result()
result

sv = result.get_statevector()
sv

plot_bloch_multivector(sv)

circuit.measure([0], [0])

simulator = qiskit.Aer.get_backend('qasm_simulator')
simulator

job = qiskit.execute(circuit, backend=simulator, shots=1024)
job

result = job.result()
result

counts = result.get_counts()
counts

from qiskit.tools.visualization import plot_histogram

plot_histogram(counts)

circuit = qiskit.QuantumCircuit(1, 1)
circuit.x(0)
circuit

simulator = qiskit.Aer.get_backend('unitary_simulator')
simulator

job = qiskit.execute(circuit, backend=simulator)
job

result = job.result()
result

unitary = result.get_unitary()
unitary

